### ISSUE TITLE
Dropbox Error

### ISSUE THREAD

**Issue by bmunsell** [leedo/noembed#68]
Dropbox embed errors with message "Can't call method "captures" on an undefined value"

https://noembed.com/demo?url=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fhtzg1ygx81h1sui%2FChick-a-Dee-12.jpg%3Fdl%3D0&maxwidth=700&nowrap=on

**Comment by leedo** [comment]
Thanks! This was caused by a big refactor recently. Should be fixed.

**Comment by bmunsell** [comment]
Image is still not appearing correctly: https://noembed.com/demo?url=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fhtzg1ygx81h1sui%2FChick-a-Dee-12.jpg%3Fdl%3D0&maxwidth=700&nowrap=on

here is original image: https://www.dropbox.com/s/htzg1ygx81h1sui/Chick-a-Dee-12.jpg?dl=0

Also, i am using this as an endpoint for ckeditor, with images the return doesnt seem to contain the noembed domain, ie: https://noembed.com/i//700/0/https://dl.dropbox.com/s/htzg1ygx81h1sui/Chick-a-Dee-12.jpg, just returns <img src="https://dl.dropbox.com/s/htzg1ygx81h1sui/Chick-a-Dee-12.jpg"> which doesnt work.

do I need to add the "https://noembed.com/i//700/0/" on my end?
